const { register,groceriess,phones,laptops,watchs,headphones,homeappliancess,login,cart,getcartData,increseqty,decreseqty,deleteCart,useradress,subscribe,Itemcounter} = require("../controler/controler")
const router = require('express').Router()
const {order,paymentVerify}=require('../controler/paymentControler')
 router.get('/',groceriess)
router.post('/api/register',register)
router.post('/auth/login', login)
router.get('/cat/watch', watchs)
router.get('/cat/smartphones', phones)
router.get('/cat/laptops', laptops)
router.get('/cat/headphone', headphones)
router.get('/cat/homeappliances', homeappliancess)
router.post('/cat/getcartData',getcartData)
router.post('/cart/cartData',cart)
router.post('/cat/increseqty',increseqty)
router.post('/cat/decreseqty',decreseqty)
router.post('/cat/deletecart',deleteCart)
router.post('/api/order/userAddress',useradress)
router.post('/api/order',order)
// router.post('/api/order/payment/verify',paymentVerify)
 router.post('/api/subscribe',subscribe)
 router.post('/item/counter',Itemcounter)
module.exports = router


